### ISSUE TITLE
Why does not publish this app to Windows Store?

### ISSUE THREAD

**Issue by soroshsabz** [WinUICommunity/TvTime#1]
ITNOA

Hi,

Why does not publish this app to Windows Store?

**Comment by ghost1372** [comment]
Hi @soroshsabz 
I would really like to see TvTime released in the MS Store, But unfortunately there are some issues. I do not have a Microsoft developer account, And I have to pay a lot of money to get it from Iran. The cost of the account is $19, which is not much But I am not able to pay from Iran, and for this I have to get a Visa or Master card through intermediaries, The cost of which is very high and I cannot pay in this difficult economic situation. I hope I can get an account through my acquaintances in Türkiye, but I'm not sure

**Comment by soroshsabz** [comment]
Ok thanks for explaining.

I hope you have more money each day.

**Comment by ghost1372** [comment]
@soroshsabz Done https://apps.microsoft.com/detail/9N8HTFJ7PVKB
