### ISSUE TITLE
crash: subtitle language

### ISSUE THREAD

**Issue by 3xploiton3** [WinUICommunity/TvTime#2]
suddenly close when click subtitle language
windows 11, 22H2

![image](https://github.com/WinUICommunity/TvTime/assets/19517680/12bbedc5-a97d-4389-8e8a-8766cc9dd518)

**Comment by ghost1372** [comment]
Hi, tnx
I know about this problem and it has already been solved, a new version will be released soon.

**Comment by ghost1372** [comment]
@3xploiton3  try new version
https://github.com/WinUICommunity/TvTime/releases/tag/v2.3.0
