### ISSUE TITLE
Availability of WinUICommunity.Components, WINUICommunity.Core and WinUICommunity.LandingPage 

### ISSUE THREAD

**Issue by masbou** [WinUICommunity/TvTime#3]
Hello,

Thanks for your great software. I just downloaded TVTime 2.3.0 source code but when compiling it I got error messages. The new package are not available. From where can I get them.
Regards

**Comment by ghost1372** [comment]
> Hello,
> 
> Thanks for your great software. I just downloaded TVTime 2.3.0 source code but when compiling it I got error messages. The new package are not available. From where can I get them.
> Regards

Hi tnx, new packages will be available soon.  If everything goes well, I will upload it to Nuget today.

**Comment by ghost1372** [comment]
@masbou Done
