### ISSUE TITLE
failed setup subtitle language

### ISSUE THREAD

**Issue by 3xploiton3** [WinUICommunity/TvTime#4]
![image](https://github.com/WinUICommunity/TvTime/assets/19517680/7f04beaa-7641-495b-9ae9-00b0ee10ffcd)

![image](https://github.com/WinUICommunity/TvTime/assets/19517680/f8908c5f-63be-4368-8ef8-917816f67320)

**Comment by ghost1372** [comment]
Thank you @3xploiton3 
Issue Fixed, Wait for v2.5.0

**Comment by 3xploiton3** [comment]
please make default language (ENGLISH) only
we can optional add another language manually

**Comment by 3xploiton3** [comment]
in my case, its annoying to remove 1 by 1 another language that doesnt relevance to me

i'm using english & indonesian language

![image](https://github.com/WinUICommunity/TvTime/assets/19517680/26a241a3-f2a7-45cf-98c2-b4d8b3ae5faa)

**Comment by ghost1372** [comment]
It is a good suggestion.
Can you create a new issue for it?
