### ISSUE TITLE
add search filter

### ISSUE THREAD

**Issue by 3xploiton3** [WinUICommunity/TvTime#5]
search at left doesn't make any sense,, TvTime only have 7 menu 

on subtitle menu, add some search filter, handysub have thiss

![image](https://github.com/WinUICommunity/TvTime/assets/19517680/5a79c68c-f1d8-4241-a60d-8200897e1387)

**Comment by ghost1372** [comment]
The search on the left is for menus, which will be removed in the next version.
For each part of the app, you can use the search that is above in the title bar
